
name: "Code Scanning - Action"
on:
  push
jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      # Build the project, including steps to (i) install tools (including compilers in the appropriate versions, 
      # package managers, and build tools), (ii) install dependencies, (iii) build the code.
      - name:
              uses: actions/checkout@v2
            - name: Install JDK 8
              run: sudo apt-get install openjdk-8-jdk
            - name: Install Apache Maven
              run: sudo apt-get install maven
            - name: Install Git
              run: sudo apt-get install git
            - name: Install Gradle
              run: sudo apt-get install gradle
            - name: Install Gradle Enterprise Plugin
              run: echo "apply plugin: 'org.gradle.enterprise'" >> settings.gradle
            - name: Install Kotlin Compiler
              run: sudo apt-get install kotlin
            - name: Install Dependencies
              run: mvn install
            - name: Build Project
              run: mvn clean package
            - name: Build Project with Gradle
              run: gradlew
            - name: Build Project with Gradle Enterprise Plugin
              run: gradlew build


      # Analyze the project using CodeQL.
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
