
name: "Code Scanning - Action"
on: push
jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      # Build the project, including steps to (i) install tools (including compilers in the appropriate versions, 
      # package managers, and build tools), (ii) install dependencies, (iii) build the code.
      - name:
        run: |
          # Install Java
          sudo apt-get install openjdk-8-jdk
          # Install Gradle
          wget https://services.gradle.org/distributions/gradle-6.3-bin.zip
          unzip gradle-6.3-bin.zip
          export PATH=$PATH:$PWD/gradle-6.3/bin
          # Build the project
          ./gradlew build


      # Analyze the project using CodeQL.
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
